name: multidino
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy==1.24.3
  - matplotlib
  - pillow
  - torch==2.4.0
  - torchvision==0.19.0
  - pytorch3d==0.7.7
  - transformers==4.45.2
  - imgaug==0.4.0
  - tqdm
  - tensorboard
  - scikit-learn==1.5.2
  - open3d==0.18.0
  - pip
  - pip:
      - webdataset==0.2.100
