name: multidino
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy==1.24.3
  - matplotlib
  - pillow
  - torch==2.4.0
  - torchvision==0.19.0
  - cudatoolkit=11.3
  - pytorch3d
  - transformers==4.45.2
  - imgaug==0.4.0
  - tqdm
  - tensorboard
  - pip
  - pip:
      - webdataset
